[package]
name = "celtchar"
version = "0.99.0"
authors = ["Thomas Letan <lthms@soap.coffee>"]

[dependencies]
toml = "0.5"
clap = "2.33"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tera = "1.0"
zip = "0.5"
libceltchar = { version = "0.99",  path = "../lib" }
ogam = "*"
